<?php
/** @var \KW\CustomerWallet\Block\Account\Wallet\WalletInfo $block */
/** @var \KW\CustomerWallet\Api\Data\WalletInterface $wallet */

$wallet = $block->getWallet();
$priceHelper = $block->getPriceHelper();
$transactions = $block->getTransactions();
$topups = $block->getTopups();
?>

<div class="block block-account-wallet-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Wallet Information')) ?></strong></div>

    <div class="block-content">
        <div class="box box-wallet-info">
            <div class='box-content'>
                <table class='wallet-summary'>
                    <tr>
                        <td><?= $block->escapeHtml(__('Public Hash:')) ?></td>
                        <td>
                            <code>
                                <strong>
                                    <?= $block->getWallet()->getPublicHash() ?>
                                </strong>
                            </code>
                        </td>
                    </tr>
                    <tr>
                        <td><?= $block->escapeHtml(__('Wallet Balance:')) ?></td>
                        <td><strong><?= $block->getWalletBalance() ?></strong></td>
                    </tr>
                    <tr>
                        <td><?= $block->escapeHtml(__('Total Orders:')) ?></td>
                        <td>
                            <strong>
                                <?= $block->getWalletTotalOrders() . ' Orders' ?>
                            </strong>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="box-actions">
                <h3 class="box-title">
                    Actions
                </h3>
                <div class="wallet-actions">
                    <a href="<?= $block->getTransferLink() ?>"
                       class='btn secondary'>Transfer Money</a>
                    <a href="<?= $block->getAddMoneyLink() ?>"
                       class='btn primary'>Add Money</a>
                </div>
                <p>
            </div>
        </div>
    </div>
</div>
<?php if (!$wallet->getIsActive()): ?>
    <div class='wallet_disabled_wrapper'></div>
<?php endif; ?>

<!-- Transactions -->
<div class='block block-account-wallet-transactions'>
    <div class='block-title'><strong><?= $block->escapehtml(__('Wallet Transactions')) ?></strong></div>

    <?php
    if ($transactions && count($transactions)) : ?>
        <div class="table-wrapper wallet-transactions-history">
            <table class="data table table-wallet-transaction-items history" id="my-wallet-transactions-table">
                <caption class="table-caption"><?= $block->escapehtml(__('wallet topups')) ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapehtml(__('Transaction #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapehtml(__('Date')) ?></th>
                    <th scope='col' class='col type'><?= $block->escapehtml(__('Type')) ?></th>
                    <th scope="col" class="col amount"><?= $block->escapehtml(__('Amount')) ?></th>
                    <th scope='col' class='col ref-order'><?= $block->escapehtml(__('Ref. order #')) ?></th>
                    <th scope='col' class='col ref-wallet'><?= $block->escapehtml(__('Ref. wallet #')) ?></th>
                    <!--                    <th scope="col" class="col actions">--><?php
                    //= $block->escapehtml(__('action'))?><!--</th>-->
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($transactions as $transaction) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(
                            __('Transaction #')
                        ) ?>"
                            class="col id">
                            <code><?= $block->escapeHtml($transaction->getTId()) ?></code>
                        </td>

                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>"
                            class="col date">
                            <?= /* @noEscape */
                            $block->formatDate($transaction->getCreatedAt()) ?>
                        </td>

                        <td data-th="<?= $block->escapeHtml(__('Type')) ?>"
                            class='col type'>
                            <?php
                            $type = strtolower($transaction->getType());
                            $labelClass = $type === 'credit' ? 'wallet-type-credit' : 'wallet-type-debit';
                            $labelText = ucfirst($type); ?>
                            <span
                                class="wallet-type-label <?= $block->escapeHtmlAttr(
                                    $labelClass
                                ) ?>">
                                <?= $block->escapeHtml($labelText) ?>
                            </span>
                        </td>

                        <td data-th="<?= $block->escapeHtml(__('Amount')) ?>"
                            class="col amount">
                            <?= /* @noEscape */
                            $priceHelper->currency($transaction->getAmount()) ?>
                        </td>

                        <td data-th="<?= $block->escapeHtml(
                            __('Ref. Order #')
                        ) ?>"
                            class="col ref-order">
                            <?= $transaction->getReferenceOrderId() ?: '--' ?>
                        </td>

                        <td data-th="<?= $block->escapeHtml(
                            __('Ref. Wallet #')
                        ) ?>"
                            class="col ref-wallet"
                            title="<?= $block->escapeHtml(
                                $transaction->getRelatedWalletId() ?: ''
                            ) ?>">
                            <code>
                                <?= $transaction->getRelatedWalletId()
                                    ? $block->escapeHtml(
                                        substr(
                                            $transaction->getRelatedWalletId(),
                                            0,
                                            8
                                        ) . '...'
                                    )
                                    : '--' ?>
                            </code>
                        </td>
                    </tr>
                <?php
                endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else : ?>
        <div class="message info empty">
            <span>
                <?= $block->escapehtml($block->getemptytransactionsmessage()) ?>
            </span>
        </div>
    <?php
    endif ?>
</div>

<!-- Topups -->
<div class='block block-account-wallet-topups'>
    <div class='block-title'><strong><?= $block->escapeHtml(__('Wallet Topups')) ?></strong></div>

    <?php
    if ($topups && count($topups)) : ?>
        <div class="table-wrapper wallet-topups-history">
            <table class="data table table-wallet-topup-items history" id="my-wallet-topups-table">
                <caption class="table-caption"><?= $block->escapeHtml(__('Wallet Topups')) ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Topup #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Amount')) ?></th>
                    <th scope='col' class='col note'><?= $block->escapeHtml(__('Note')) ?></th>
                    <!--                    <th scope="col" class="col actions">--><?php
                    //= $block->escapeHtml(__('Action'))?><!--</th>-->
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($topups as $topup) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Topup #')) ?>" class="col id"><?= $block->escapeHtml(
                            $topup->getId()
                        ) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */
                        $block->formatDate($topup->getCreatedAt()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Amount')) ?>" class="col total"><?= /* @noEscape */
                        $priceHelper->currency($topup->getAmount()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Note')) ?>" class='col note'><?= /* @noEscape */
                            $topup->getNote() ?? '--' ?></td>
                    </tr>
                <?php
                endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php else : ?>
        <div class="message info empty">
            <span>
                <?= $block->escapeHtml($block->getEmptyTopupsMessage()) ?>
            </span>
        </div>
    <?php
    endif ?>
</div>
