<?php
/** @var \KW\CustomerWallet\Block\Account\Wallet\WalletTopup $block */
?>

<div class="block block-wallet-topup">
    <div class="block-content">
        <form class="form form-wallet-topup"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method='post'
              id='wallet-topup-form'
              data-mage-init='{"validation":{}, "Magento_Ui/js/form/loader": {}}'>

            <?= $block->getBlockHtml('formkey'); ?>

            <fieldset class='fieldset info'>
                <!-- Amount -->
                <div class='field required'>
                    <label class='label' for='amount'>
                        <span><?= __('Amount') ?></span>
                    </label>
                    <div class="control">
                        <input type="number"
                               step="0.01"
                               name="amount"
                               id="amount"
                               value=""
                               min="0.01"
                               title="<?= __('Amount') ?>"
                               class="input-text"
                               data-validate="{required:true, 'validate-number':true, 'greater-than-zero':true}"/>
                        <div class="note">
                            <?= __('Enter the amount to add to your wallet (decimals allowed).') ?>
                        </div>
                    </div>
                </div>

                <!-- Note -->
                <div class="field">
                    <label class="label" for="note">
                        <span><?= __('Note') ?></span>
                    </label>
                    <div class="control">
                        <textarea name="note"
                                  id="note"
                                  title="<?= __('Note') ?>"
                                  class="input-text"
                                  rows="4"></textarea>
                    </div>
                </div>
            </fieldset>

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit"
                            class="action save primary">
                        <span><?= __('Add Money') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
